### ISSUE TITLE
false positve error

### ISSUE THREAD

**Issue by Xaver222** [sVerentsov/Circuit-Checker-Factorio#2]
There is one bug, it will display as error even trough the game can use combinators in this way.
![2023-05-07 20_25_16-Window](https://user-images.githubusercontent.com/104947099/236696062-09e8b888-f944-4353-bbca-c09382c3eb90.png)
![2023-05-07 20_24_52-Window](https://user-images.githubusercontent.com/104947099/236696065-48dc3901-25e4-4b53-8e90-5b7e458cdf81.png)
![2023-05-07 20_24_26-Window](https://user-images.githubusercontent.com/104947099/236696066-6162bc5c-9559-4f05-877f-7e55101a9526.png)

Input any, and output a signal, as input counter, will work even there is no input signal of this kind present

**Comment by Xaver222** [comment]
another one, if one input is set to a constant number:
![2023-05-07 20_50_48-Window](https://user-images.githubusercontent.com/104947099/236696999-66592e97-07cc-47af-aa92-d44d20b55da1.png)

**Comment by sVerentsov** [comment]
Will check, thank you for the report!

**Comment by sVerentsov** [comment]
@Xaver222 Updated in 1.1.4, could you please check if I understood your cases correctly?

**Comment by Xaver222** [comment]
@sVerentsov Thnx for the fast response!
Yeah both fixed. Just minior thing in the change log you point out:
"Fixed false positive when **first** argument to arithmetic combinator is a constant"
in game someone can put constat number in any of the two input slots,
I just checked and your fix work even if first input is signal and second input is constant. So everything is fine. 
Thnx again

**Comment by sVerentsov** [comment]
Constant second argument worked before, so I didn't mention it in the changelog
